server:
  port : 5000
spring:
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MYSQL8Dialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}