spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: b1e2e5b7129550c65635ecffe688d2dc #REST API 키
            redirect-uri: http://localhost:8080/login/kakao #인가 코드가 리다이렉트된 URI
            client-authentication-method: POST
            client-secret: ovycgatXmy4CqR7cSdRSEi7SduUFNY69 #토큰 발급 시 보안 강화 위해 추가 확인하는 코드
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#jwt 토큰
jwt:
  token:
    secret-key: [secret-key]
  access-token:
    expire-length: 1800000
  refresh-token:
    expire-length: 1209600000