spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: b1e2e5b7129550c65635ecffe688d2dc #REST API 키
            redirect-uri: http://localhost:8080/login/kakao #인가 코드가 리다이렉트된 URI
            client-authentication-method: POST
            client-secret: ovycgatXmy4CqR7cSdRSEi7SduUFNY69 #토큰 발급 시 보안 강화 위해 추가 확인하는 코드
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

#jwt 토큰
jwt:
    secret: d9jfAaD3FJDsIFSiof38r2S8iik9fds8FE4G734y1VN9B4Pjh4Unre42OlwHkTfKD0df3Diu9mlC0eSPkw1qGEd3QtdAH4V0b32ssYew #512비트(64바이트) 이상