POST https://api.ndayschallenge.com/auth/login
Content-Type: application/json

{
  "id": "jaerong@gmail.com",
  "pw": "!Jinwoo4318"
}

### 개인 챌린지 생성
POST http://localhost:8080/challenge
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZDEyM0BnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjgyNjYzODI1fQ.b5CwSseC6pa9IKi0yWu5siljRFAyJefE4I2QPQmerTs

{
  "name": "명상",
  "category": "MINDFULNESS",
  "reward": "",
  "passCount": 10,
  "startDate": "2023-01-11",
  "totalDays": 10,
  "type": "SINGLE",
  "successCount": 0,
  "usedPassCount" : 0
}

### 그룹 챌린지 생성
POST http://localhost:8080/challenge/group
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZDEyM0BnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjgyNjYzODI1fQ.b5CwSseC6pa9IKi0yWu5siljRFAyJefE4I2QPQmerTs

{
  "name": "공부",
  "category": "MINDFULNESS",
  "reward": "암거나",
  "passCount": 10,
  "startDate": "2022-12-01",
  "totalDays": 10,
  "type": "GROUP",
  "successCount": 0,
  "usedPassCount" : 0,
  "memberNumber": 4,
  "groupMembers": [2]
}

### 챌린지 상세
GET https://api.ndayschallenge.com/challenge/5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWVyb25nQGdtYWlsLmNvbSIsImF1dGgiOiJudWxsIiwiZXhwIjoxNjgwMjUyMzUwfQ.4SWIsNgtmXdqiUX4umTgcPAnyGwg4Bmqj9gD9J5RJk0

### 진행 챌린지
GET https://api.ndayschallenge.com/challenge/list
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqYWVyb25nQGdtYWlsLmNvbSIsImF1dGgiOiJudWxsIiwiZXhwIjoxNjgwMjUyMzUwfQ.4SWIsNgtmXdqiUX4umTgcPAnyGwg4Bmqj9gD9J5RJk0

### 완료 챌린지
GET https://api.ndayschallenge.com/user/finishedChallenges
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJjY2NjQG5hdmVyLmNvbSIsImF1dGgiOiJudWxsIiwiZXhwIjoxNjcxODAyMzgyfQ.a37jUUdbvsd8OS7yetYdyVPwL0OpuGXCJ444y9I1PZk

### 챌린지 삭제
DELETE https://api.ndayschallenge.com/challenge/8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYWFhQG5hdmVyLmNvbSIsImF1dGgiOiJudWxsIiwiZXhwIjoxNjcxODQ5NTE4fQ.ShbQk6X3iZ3g7f06fOvPeUvUdQkUu_ybX4bLVUrzKsI

### 스탬프 찍기
POST https://api.ndayschallenge.com/challenge/stamp
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYWFhQG5hdmVyLmNvbSIsImF1dGgiOiJudWxsIiwiZXhwIjoxNjczNzY2Nzk1fQ.0naUqyxTo7f96vWTH35aG7QnbId9fnPyHtfCSdRZNhE

{
  "roomNumber": 1,
  "stampNumber": 1,
  "day":"o"
}