GET http://localhost:8080/friends/find
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZDEyQGdtYWlsLmNvbSIsImF1dGgiOiJudWxsIiwiZXhwIjoxNjc1NzU2Njc1fQ.ddJCOT5SMEbwalhUuKom8bw3NkM1TThPOC9kioeNE8M

{
  "id": "wonsy1006@gmail.com",
  "nickname": ""
}