GET http://localhost:8080/friends/find?id=&nickname=ab
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZDEyQGdtYWlsLmNvbSIsImF1dGgiOiJudWxsIiwiZXhwIjoxNjc1ODMzODI3fQ.z5iPB7C2LbKJLVxI_N5yfqR5h655xp5imNE7rMIzrwU
