###회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "id": "id123@gmail.com",
  "pw": "123",
  "nickname": "닉네임2",
  "image": 2
}


###로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "id": "id1234@gmail.com",
  "pw": "123"
}

###로그아웃
POST http://localhost:8080/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZDEyM0BnbWFpbC5jb20iLCJhdXRoIjoibnVsbCIsImV4cCI6MTY3NzEzNjI1N30.AdgpSVN-AQiYjW6JMHmTAtH7xGanK77_-Y-CPVB1FKU
Content-Type: application/json


###액세스 토큰 재발급
POST http://localhost:8080/auth/reissue
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZDEyM0BnbWFpbC5jb20iLCJhdXRoIjoibnVsbCIsImV4cCI6MTY3OTM4MTc5MH0.8n8O0K7AkFJyXF__VMt7VD3awyuoP-EVNGhBnaYL9-8
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZDEyM0BnbWFpbC5jb20iLCJhdXRoIjoibnVsbCIsImV4cCI6MTY3OTM4MTc5MH0.8n8O0K7AkFJyXF__VMt7VD3awyuoP-EVNGhBnaYL9-8",
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2Nzk5ODQ3OTB9.QfqDDA8b9YobpJS8idgCEt3Idx-q0e0ZAunYK_8qhGk"
}