###회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "id": "aaee819@gmail.com",
  "pw": "123",
  "nickname": "bcd91",
  "image": 3
}


###로그인
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "id": "aaee89@gmail.com",
  "pw": "123"
}


###액세스 토큰 재발급
POST http://localhost:8080/auth/reissue
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYWVlODlAZ21haWwuY29tIiwiYXV0aCI6Im51bGwiLCJleHAiOjE2NzUwOTUxNTd9.0Y7urKOhzdMPcyqsXiPHUgM_KUFIq8ValqguPbFt7N8
Content-Type: application/json

{
  "accessToken": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYWVlODlAZ21haWwuY29tIiwiYXV0aCI6Im51bGwiLCJleHAiOjE2NzUwOTUxNTd9.0Y7urKOhzdMPcyqsXiPHUgM_KUFIq8ValqguPbFt7N8",
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NzU2OTgxNTd9.QTLDl2f0IzpN12JyKqqvRczVPCL5BTe3zvfuluiVteo"
}