# 다짐 등록
POST http://localhost:8080/challenge/11/dajim
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmMzQGdtYWlsLmNvbSIsImF1dGgiOiJudWxsIiwiZXhwIjoxNjczMjQxNTQ4fQ.UPIB87wIzrm2BaKRPNXlwAjejsCsO6IdluWxeFHYBjw


{
  "content": "다짐 등록2",
  "open": "PRIVATE"
}

###

# 다짐 수정
PATCH http://localhost:8080/challenge/10/dajim
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhYmMxMjNAZ21haWwuY29tIiwiYXV0aCI6Im51bGwiLCJleHAiOjE2NzI5MjAyMTR9.nZpB3-15bEGERYvsEAbzjWKbNvVVoyr3wbhgVtwVsVI

{
  "dajimNumber": 7,
"content": "다짐 수정1111",
"open": "PUBLIC"
}

###

# 챌린지룸 다짐 불러오기
GET http://localhost:8080/challenge/1/dajim
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyNEBuYXZlci5jb20iLCJhdXRoIjoibnVsbCIsImV4cCI6MTY3MjQwMTg2N30.tqCb9no1R8GhmWaXGF2DBvqUOR_8W92iSq-K8J_ia70

###

# 피드 조회
GET http://localhost:8080/feed
Content-Type: application/json

