### 다짐 등록
POST http://localhost:8080/challenge/2/dajim
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZDEyM0BnbWFpbC5jb20iLCJhdXRoIjoibnVsbCIsImV4cCI6MTY4MDg4NTgzMX0.K4rothmF7hk0fsjFkMZOFpEjTKL9dRVDBe4K6zZrwoc

{
  "content": "6번 방의 선물",
  "open": "PUBLIC"
}

### 다짐 수정
PATCH http://localhost:8080/challenge/10/dajim
Content-Type: application/json
Authorization: Bearer

{
  "dajimNumber": 7,
"content": "다짐 수정1111",
"open": "PUBLIC"
}

### 챌린지룸 내 다짐 조회
GET http://localhost:8080/challenge/1/dajim
Content-Type: application/json
Authorization: Bearer

### 피드 조회
GET http://localhost:8080/feed
Content-Type: application/json