POST http://localhost:8080/feed/emotion
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMkBuYXZlci5jb20iLCJhdXRoIjoibnVsbCIsImV4cCI6MTY3MjkxNDg3Mn0.uiE03dWKNsNukizx2hqq_ek_ylt6QHcL55DwH6jLN-s

{
  "dajimNumber": 6,
  "sticker": "WATCH"
}