# Request
GET http://localhost:8080/user/details
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMUBuYXZlci5jb20iLCJhdXRoIjoibnVsbCIsImV4cCI6MTY3MjkwNjUwOH0.tUcjHITnRCmXThlcnFoLSpoYlEggxHgXI2BcOqXA2nU

