### 회원정보 조회
GET http://localhost:8080/user/details
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZDEyM0BnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjgyNjYzODI1fQ.b5CwSseC6pa9IKi0yWu5siljRFAyJefE4I2QPQmerTs


### 회원정보 수정
PATCH http://localhost:8080/user/edit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZDEyM0BnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjgyNjY0OTI3fQ.tHjGo9-CjOKgM7TdRn8fWOSKfv_YWTjhEHxnf0VEsM8

{
  "pw": "123",
  "nickname": "바꾸깅2",
  "image": 3
}


### 회원 탈퇴
DELETE http://localhost:8080/user/withdrawal
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZDEyM0BnbWFpbC5jb20iLCJhdXRoIjoibnVsbCIsImV4cCI6MTY4MTAyODY2NX0.ch-6PPxd9OYa8pfuYVFF5_7F5uZZm6kQ3UXut4hGKlU

