### 회원정보 조회
GET http://localhost:8080/user/details
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZDEyMzQ1NjdAZ21haWwuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImV4cCI6MTY4NzUxNzMzOX0.k8w5MbsJG3pWPdDeOwc4rPIm5SgGuwPr3LkN2DmuU5Q


### 회원정보 수정
PATCH http://localhost:8080/user/edit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZDEyM0BnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NzQzNTE2fQ.R7RFFsaPyPSXFcTgZHmbQdWk-QFC4sI2mJHwRHwTUFk

{
  "pw": "123",
  "nickname": "바꾸깅깅깅",
  "image": 3
}


### 회원 탈퇴
DELETE http://localhost:8080/user/withdrawal
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJpZDEyM0BnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjg0NzQzNTE2fQ.R7RFFsaPyPSXFcTgZHmbQdWk-QFC4sI2mJHwRHwTUFk

